### ISSUE TITLE
MVPリリースレビュー依頼提出

### ISSUE THREAD

**Issue by MaikoSuwazono** [MaikoSuwazono/DayOutLog#36]

**Comment by MaikoSuwazono** [comment]
## 各種情報
サービスの概要とMVPで検証する事柄：
1日で行った行き先を時系列形式で投稿できるアプリです。
行き先ごとに写真やお店などの住所を登録でき、登録した住所はGoogleMap上でピンで表示されるようになっています。
ユーザー登録/認証、記事の投稿と表示が問題なくできているか検証が必要です。

サービス名：DayOutLog
サービスURL：https://dayoutlog-ffb534a7ebc0.herokuapp.com/


## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] ユーザー登録、認証機能
- [ ] 記事投稿機能
- [ ] 記事内の行き先で行き先の住所を登録する機能
- [ ] 記事内の行き先をマップ上にピンで表示する機能

## READMEレビュー時から変更した機能
- [ ] コメント、いいね機能
- [ ] 検索機能

## サービスイメージがわかるようなスクリーンショット等
[![Image from Gyazo](https://i.gyazo.com/03fd10fe7aea6f4338bb220ea8e0cf0d.jpg)](https://gyazo.com/03fd10fe7aea6f4338bb220ea8e0cf0d)
[![Image from Gyazo](https://i.gyazo.com/652b89184b0d4c37774845b50dd9c56a.jpg)](https://gyazo.com/652b89184b0d4c37774845b50dd9c56a)

**Comment by tarakish** [comment]
確認しました👍️
新規投稿について、以下のように作成ができませんでした。
一度ご確認をお願いします。
[![Image from Gyazo](https://i.gyazo.com/c67b0c40c110c62f75c9c6ad415e5dd8.gif)](https://gyazo.com/c67b0c40c110c62f75c9c6ad415e5dd8)

添付ファイルは以下のものを使用しました。
![on_the_rocks](https://github.com/user-attachments/assets/c13fa1cf-5338-4a42-a0b5-02f5898ae240)

**Comment by MaikoSuwazono** [comment]
レビューありがとうございます！
上記について確認しましたが、「行き先を追加」ボタンを押した後少し時間がかかるものの、次の画面に遷移されました。
また、画像の保存について、以下の記事を参考に画像がAWSのS3に保存されるように修正しました。
[Rails+CarrierWave+heroku環境でAWS S3へ画像をアップロードする](https://qiita.com/nobu0717/items/a34a896f6e7ad68dc54e)

お手数ですが、再度ご確認をお願いいたします。

**Comment by kenchasonakai** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
