### ISSUE TITLE
Googleログイン

### ISSUE THREAD

**Issue by MaikoSuwazono** [MaikoSuwazono/DayOutLog#44]

**Comment by MaikoSuwazono** [comment]
## 解決したいこと・達成したいものについて
Googleアカウントを使用したユーザー認証機能を作成したい

## 聞きたいこと・アドバイスが欲しいこと
Googleのログイン画面に遷移するも、以下エラーが出て認証に進めません。
[![Image from Gyazo](https://i.gyazo.com/11fd58ce3410fc63466be06c1302f44d.png)](https://gyazo.com/11fd58ce3410fc63466be06c1302f44d)

redirect_uri_mismatchとのことで設定している箇所を確認しましたが、同じURLを指定しているように見え、原因が特定できていません。

▼GoogleCloud
[![Image from Gyazo](https://i.gyazo.com/e9bbe4bb1ad3069ed87948b5a27451be.png)](https://gyazo.com/e9bbe4bb1ad3069ed87948b5a27451be)

▼config/initializers/sorcery.rb
```
  config.google.key = Rails.application.credentials.dig(:google, :google_client_id)
  config.google.secret = Rails.application.credentials.dig(:google, :google_client_secret)
  config.google.callback_url = "http://localhost:3000/oauth/callback?provider=google"
  config.google.user_info_mapping = {:email => "email", :name => "name"}
```

## 実装の際に参考にした資料等
以下記事を参考に、SorceryのExternal機能を使用したGoogleアカウントでのユーザー認証機能を作成しています。
[External · Sorcery/sorcery Wiki](https://github.com/Sorcery/sorcery/wiki/External)
[【Rails】Sorceryを使用したGoogle認証機能の追加 #Ruby - Qiita](https://qiita.com/okada84108983/items/0c84c01b88072c004873)

## 現状のコードの状態がわかるURL(プルリクエスト・リポジトリ等)
https://github.com/MaikoSuwazono/DayOutLog/pull/43

## 現状のコードの状態がわかるURLのどこが関係していると考えているのか
Googleでの認証画面に遷移する際に、URLにパラメーターなどが付与されURLが不一致となっているのではないかと考えています。

## 検証した結果から分かったこと・考えたこと
ログインボタンクリック時のターミナルを確認しましたが、遷移自体は問題なくできているようです。
```
Started GET "/oauth/google" for ::1 at 2024-11-28 15:30:50 +0900
Processing by OauthsController#oauth as HTML
  Parameters: {"provider"=>"google"}
Redirected to https://accounts.google.com/o/oauth2/auth?client_id=464964745462-r6872qs68i1040sa1f26vfi358u8jlaa.apps.googleusercontent.com&display&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Foauth%2Fcallback%3Fprovider%3Dgoogle&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&state
Completed 302 Found in 2ms (ActiveRecord: 0.0ms | Allocations: 795)
```

**Comment by kenchasonakai** [comment]
原因はっきりとわかりませんが、開発用の設定にしていたらGoogleのOAuth 同意画面にログインに使用するアカウントが追加されているか確認してみてください

**Comment by MaikoSuwazono** [comment]
ご確認いただきありがとうございます。
以下確認しましたが、ログインに使用するアカウントは追加できている認識です。[![Image from Gyazo](https://i.gyazo.com/5fc314073c245c7482c39f3fff027a41.png)](https://gyazo.com/5fc314073c245c7482c39f3fff027a41)

**Comment by kenchasonakai** [comment]
git cloneして試してみましたが、config.google.keyとconfig.google.secretに自分のクライアント IDとクライアント シークレットを設定したら正常に動きましたので、正しいクライアント IDとクライアント シークレットの設定が出来ているか、`Rails.application.credentials.dig`を使って呼び出せているか、設定が反映されているか(config系は設定をしてもサーバーの再起動をしないと反映されないことがあります)を確認してみるとよいかなと思います
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/09ca1d12e2063a9b902c972f7d1c678e.gif)](https://startup-technology.gyazo.com/09ca1d12e2063a9b902c972f7d1c678e)

**Comment by MaikoSuwazono** [comment]
回答が遅くなってしまい申し訳ございません。
こちらについて、原因はconfig/initializers/sorcery.rbに設定していたconfig.google.callback_urlの値がGoogle OAuth上の設定と異なっていたためでした。
 Google  OAuthでは"?provider=google"を含めていなかったので、含めたところ問題なく認証されました。
(パラメーターは設定不要と思い込んでいました…)

この件はクローズさせていただきます。
ご対応いただきありがとうございました。
