### ISSUE TITLE
看板レビュー依頼

### ISSUE THREAD

**Issue by MaikoSuwazono** [MaikoSuwazono/DayOutLog#7]
■Webアプリの概要
このWebアプリの説明を500文字以下で記載してください。

■1週間辺りの開発に向けられる時間
- 1週間あたり：18時間

■ProjectsのURL
https://github.com/users/MaikoSuwazono/projects/2/views/1?pane=issue&itemId=81741797

■MVPリリースまで
- [ ] rails new
- [ ] Herokuにデプロイ
- [ ] トップページ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] 記事投稿機能
- [ ] コメント機能
- [ ] いいね機能
- [ ] 記事検索機能

■MVP後
- [ ] GoogleMap
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] ユーザー情報更新
- [ ] レスポンシブ対応

■MVPレビュー依頼予定日
予定日：2024年 11月 5日

**Comment by Mariko222** [comment]
ご提出ありがとうございます。
概ね良いかと思います、LGTMです！
